'use strict';
const $=id=>document.getElementById(id);
const SAVE_KEY='mini-browser-hero-v13';
const KILLS_TO_CLEAR=5;
const RARITIES=[['common','コモン',5200,1],['rare','レア',2600,1.35],['epic','エピック',1300,1.85],['legendary','レジェンダリー',650,2.6],['divine','ディヴァイン',180,3.5],['celestial','セレスティアル',55,4.4],['arcana','アルカナ',12,5.4],['beyond','ビヨンド',3,6.8],['cosmic','コズミック',1,8.5]];
const SLOTS={weapon:'武器',shield:'盾',helm:'兜',armor:'鎧',gloves:'腕',boots:'足',ring:'リング',amulet:'アミュレット'};
const ICON={weapon:'⚔️',shield:'🛡️',helm:'⛑️',armor:'🧥',gloves:'🧤',boots:'🥾',ring:'💍',amulet:'🔱'};
const SLOT_GROUP={weapon:'weapon',shield:'armor',helm:'armor',armor:'armor',gloves:'armor',boots:'armor',ring:'ring',amulet:'ring'};
const MAT_NAME={weapon:'武器石',armor:'防具石',ring:'装飾石'};
const defaultState={lv:1,exp:0,gold:0,hp:104,world:1,area:1,maxStage:1,kills:0,chests:0,materials:{weapon:0,armor:0,ring:0},inventory:[],equipped:{weapon:null,shield:null,helm:null,armor:null,gloves:null,boots:null,ring:null,amulet:null},sound:{muted:false,volume:.35},debug:false};
let state=load(), enemy=makeEnemy(), dying=false, spawning=true, selectedEquipSlot=null;
let lastHeroAttack=performance.now(), lastEnemyAttack=performance.now(), lastSave=performance.now(), audioCtx=null;
function clone(o){return JSON.parse(JSON.stringify(o));}
function load(){try{const raw=localStorage.getItem(SAVE_KEY)||localStorage.getItem('mini-browser-hero-v12')||localStorage.getItem('mini-browser-hero-v7');if(!raw)return clone(defaultState);const old=JSON.parse(raw);const s={...clone(defaultState),...old};s.sound={...defaultState.sound,...(old.sound||{})};s.materials={...defaultState.materials,...(old.materials||{})};s.equipped={...defaultState.equipped,...(old.equipped||{})};s.inventory=Array.isArray(old.inventory)?old.inventory.map(normalizeItem):[];Object.keys(s.equipped).forEach(k=>{if(s.equipped[k])s.equipped[k]=normalizeItem(s.equipped[k],k)});return s}catch(e){return clone(defaultState)}}
function normalizeItem(i,fallback){i={...i};if(i.slot==='ring'&&/オーブ/.test(i.name||''))i.name=i.name.replace('オーブ','リング');if(i.slot==='armor'&&fallback&&fallback!=='armor')i.slot=fallback;if(!SLOTS[i.slot])i.slot=fallback||'weapon';i.upgrade=i.upgrade||0;return i}
function save(show=false){localStorage.setItem(SAVE_KEY,JSON.stringify(state));if(show)addLog('保存した！')}
function stageNo(){return (state.world-1)*10+state.area} function stageText(){return `${state.world}-${state.area}`} function setStageByNo(n){state.world=Math.floor((n-1)/10)+1;state.area=((n-1)%10)+1} function maxStageNo(){return state.maxStage||1}
function itemBonusValue(i,k){if(!i)return 0;const up=i.upgrade||0;return Math.floor((i[k]||0)*(1+up*.13))+(k==='atk'||k==='def'?up*2:0)+(k==='hp'?up*8:0)+(k==='speed'?up*8:0)}
function bonus(){const b={atk:0,def:0,hp:0,speed:0,leech:0,reduce:0,crit:0};Object.values(state.equipped).forEach(i=>{if(i)Object.keys(b).forEach(k=>b[k]+=itemBonusValue(i,k))});return b}
function stats(){const b=bonus();return{maxHp:90+state.lv*14+b.hp,atk:8+state.lv*3+b.atk,def:Math.floor(state.lv*.8+b.def),interval:Math.max(320,1100-state.lv*5-b.speed),leech:Math.min(30,b.leech),reduce:Math.min(75,b.reduce),crit:Math.min(.55,.08+b.crit/100)}}
function expNeed(){return 60+state.lv*32}
function makeEnemy(){const n=stageNo(),boss=state.area===10||state.kills===KILLS_TO_CLEAR-1,base=36+n*18+Math.pow(n,1.18)*8,hp=Math.floor(base*(boss?2.7:1));return{name:boss?`ボス ${stageText()}`:`スライム ${stageText()}`,boss,hp,maxHp:hp,atk:Math.floor((5+n*1.7)*(boss?1.65:1)),gold:Math.floor((10+n*4)*(boss?3:1)),exp:Math.floor((14+n*6)*(boss?3:1))}}
function heroAttack(){if(dying||spawning)return;const s=stats(),crit=Math.random()<s.crit,dmg=Math.max(1,Math.floor((s.atk+rand(0,4))*(crit?1.8:1)));enemy.hp-=dmg;if(s.leech>0)state.hp=Math.min(s.maxHp,state.hp+Math.ceil(dmg*s.leech/100));showSlash();showDamage((crit?'CRIT ':'')+dmg);flash('enemy');play(crit?'crit':'hit');if(enemy.hp<=0)defeatEnemy()}
function enemyAttack(){if(dying||spawning)return;const s=stats(),dmg=Math.max(1,Math.floor(Math.max(1,enemy.atk-s.def+rand(0,3))*(1-s.reduce/100)));state.hp-=dmg;flash('hero');if(state.hp<=0){state.hp=Math.ceil(s.maxHp*.45);state.gold=Math.max(0,Math.floor(state.gold*.9));play('down');addLog('倒れた！Goldを少し落として復活')}}
function defeatEnemy(){if(dying)return;dying=true;enemy.hp=0;const dead={...enemy},el=$('enemy');el.className='unit enemy dead';play(dead.boss?'boss':'win');setTimeout(()=>{state.gold+=dead.gold;state.exp+=dead.exp;state.kills++;addLog(`${dead.name}を倒した！ +${dead.gold} Gold / +${dead.exp} EXP`);rollChest(dead.boss);levelCheck();if(state.kills>=KILLS_TO_CLEAR)nextStage();enemy=makeEnemy();dying=false;spawnEnemy();renderAll()},560)}
function spawnEnemy(){spawning=true;const el=$('enemy');$('enemyName').textContent=enemy.name;el.className='unit enemy walking enter';if(enemy.boss)el.classList.add('boss');setTimeout(()=>{spawning=false;lastHeroAttack=performance.now();lastEnemyAttack=performance.now()},760)}
function nextStage(){const n=stageNo()+1;setStageByNo(n);state.maxStage=Math.max(maxStageNo(),n);state.kills=0;pop('stageClear');addLog(`ステージ ${stageText()} 開放！`);refreshStageSelect()}
function levelCheck(){let up=false;while(state.exp>=expNeed()){state.exp-=expNeed();state.lv++;state.hp=stats().maxHp;up=true;addLog(`レベルアップ！ Lv${state.lv}`)}if(up){pop('levelUp');play('level')}}
function rollChest(boss){if(boss||Math.random()<.14){state.chests++;pop('chestAnim');play('chest');addLog(boss?'ボス宝箱が落ちた！':'宝箱が落ちた！')}}
function openChest(){if(state.chests<=0)return addLog('宝箱がないよ');state.chests--;const n=stageNo(),gold=rand(20+n*5,55+n*10),exp=rand(10+state.lv*5,38+state.lv*8);state.gold+=gold;state.exp+=exp;const mt=['weapon','armor','ring'][rand(0,2)],mq=rand(1,3)+(Math.random()<.16?rand(2,5):0);state.materials[mt]+=mq;let msg=`宝箱を開けた！ +${gold} Gold / +${exp} EXP / ${MAT_NAME[mt]} +${mq}`;if(Math.random()<.62){const item=makeItem();state.inventory.unshift(item);state.inventory=state.inventory.slice(0,49);msg+=` / 装備：${item.name}`;play('drop')}pop('chestAnim');play('open');addLog(msg);levelCheck();renderAll();save()}
function pickRarity(){let total=RARITIES.reduce((a,r)=>a+r[2],0),roll=Math.random()*total;for(const r of RARITIES){roll-=r[2];if(roll<=0)return r}return RARITIES[0]}
function makeItem(){const slots=Object.keys(SLOTS),slot=slots[rand(0,slots.length-1)],r=pickRarity(),n=stageNo(),p=Math.max(1,Math.floor((state.lv+n*1.5)*r[3]));const i={id:Date.now().toString(36)+Math.random().toString(36).slice(2),slot,cls:r[0],rarity:r[1],upgrade:0,atk:0,def:0,hp:0,speed:0,leech:0,reduce:0,crit:0};if(slot==='weapon'){i.atk=p+rand(1,6);i.crit=rand(0,Math.floor(p/3))}else if(SLOT_GROUP[slot]==='armor'){i.def=Math.floor(p/2)+rand(1,5);i.hp=p*4+rand(8,24);i.reduce=rand(0,Math.floor(p/4));if(slot==='shield')i.def+=rand(1,5);if(slot==='boots')i.speed=rand(5,Math.max(6,p));if(slot==='gloves')i.atk=rand(0,Math.floor(p/3))}else{i.atk=rand(0,Math.floor(p/2));i.hp=rand(0,p*2);i.speed=20+Math.floor(p*2.2);i.leech=rand(0,Math.floor(p/4));if(slot==='amulet')i.crit=rand(0,Math.floor(p/3))}const base={weapon:'ソード',shield:'シールド',helm:'ヘルム',armor:'アーマー',gloves:'ガントレット',boots:'ブーツ',ring:'リング',amulet:'アミュレット'}[slot];const prefix={cosmic:'次元の',beyond:'超越の',arcana:'秘奥の',celestial:'星天の',divine:'神威の'}[i.cls]||i.rarity;i.name=prefix+base;return i}
function power(i){return i?itemBonusValue(i,'atk')+itemBonusValue(i,'def')+Math.floor(itemBonusValue(i,'hp')/4)+Math.floor(itemBonusValue(i,'speed')/12)+itemBonusValue(i,'leech')*2+itemBonusValue(i,'reduce')*2+itemBonusValue(i,'crit'):0}
function equipItem(id){const idx=state.inventory.findIndex(i=>i.id===id);if(idx<0)return;const item=state.inventory.splice(idx,1)[0],old=state.equipped[item.slot];if(old)state.inventory.unshift(old);state.equipped[item.slot]=item;hideTip();hideDetail();play('equip');addLog(`${item.name}を装備した`);renderAll();save()}
function sellItem(id){const idx=state.inventory.findIndex(i=>i.id===id);if(idx<0)return;const item=state.inventory.splice(idx,1)[0],g=Math.max(5,power(item)*4);state.gold+=g;hideTip();hideDetail();play('sell');addLog(`${item.name}を売却 +${g} Gold`);renderAll();save()}
function bulkSell(){if(!state.inventory.length)return addLog('売却する装備がないよ');if(!confirm('倉庫内の装備をすべて売却する？'))return;let g=0,c=state.inventory.length;state.inventory.forEach(i=>g+=Math.max(5,power(i)*4));state.inventory=[];state.gold+=g;hideTip();hideDetail();play('sell');addLog(`一括売却：${c}個 / +${g} Gold`);renderAll();save()}
function selectEquip(slot){if(!state.equipped[slot]){selectedEquipSlot=null;addLog(`${SLOTS[slot]}は未装備だよ`)}else{selectedEquipSlot=slot;play('equip')}renderAll()}
function upgradeSelected(){const item=selectedEquipSlot&&state.equipped[selectedEquipSlot];if(!item)return addLog('強化する装備を選んでね');const group=SLOT_GROUP[selectedEquipSlot],need=(item.upgrade||0)+1;if(state.materials[group]<need)return addLog(`${MAT_NAME[group]}が${need}個必要`);state.materials[group]-=need;item.upgrade=(item.upgrade||0)+1;state.hp=Math.min(stats().maxHp,state.hp+20);play('equip');pop('upgradePop');addLog(`${item.name}を+${item.upgrade}に強化！`);renderAll();save()}
function heal(){const c=Math.max(10,Math.floor(stats().maxHp*.25));if(state.gold<c)return addLog(`回復には${c} Gold必要`);state.gold-=c;state.hp=stats().maxHp;play('heal');addLog('全回復した');renderAll();save()}
function sortInventory(){state.inventory.sort((a,b)=>power(b)-power(a));renderAll();save()}
function toggleDebug(){state.debug=!state.debug;addLog(state.debug?'デバッグモードON':'デバッグモードOFF');renderAll();save()}
function debugAddChests(){if(!state.debug)return addLog('デバッグモードをONにしてね');state.chests+=10;pop('chestAnim');play('chest');addLog('デバッグ：宝箱 +10');renderAll();save()}
function changeStage(){const n=Number($('stageSelect').value);setStageByNo(n);state.kills=0;enemy=makeEnemy();spawnEnemy();addLog(`ステージ ${stageText()} へ移動`);renderAll();save()}
function refreshStageSelect(){const sel=$('stageSelect');sel.innerHTML='';for(let n=1;n<=maxStageNo();n++){const o=document.createElement('option');o.value=n;o.textContent=`${Math.floor((n-1)/10)+1}-${((n-1)%10)+1}`;if(n===stageNo())o.selected=true;sel.appendChild(o)}}
function renderAll(){document.body.classList.toggle('debug',state.debug);const s=stats();state.hp=Math.min(state.hp,s.maxHp);$('topStats').innerHTML=[`Lv ${state.lv}`,`Gold ${state.gold}`,`Stage ${stageText()}`,`宝箱 ${state.chests}`,`素材 ${state.materials.weapon}/${state.materials.armor}/${state.materials.ring}`].map(x=>`<span class="stat-pill">${x}</span>`).join('');$('stageLabel').textContent=stageText();$('openChestBtn').textContent=`宝箱を開ける ×${state.chests}`;$('muteBtn').textContent=state.sound.muted?'SE OFF':'SE ON';$('volume').value=Math.round(state.sound.volume*100);$('debugModeBtn').textContent=state.debug?'デバッグON':'デバッグOFF';$('heroStats').innerHTML=`<div>攻撃力 ${s.atk}</div><div>防御力 ${s.def}</div><div>最大HP ${s.maxHp}</div><div>攻撃速度 ${Math.round(1000/s.interval*100)/100}/秒</div><div>撃破 ${state.kills}/${KILLS_TO_CLEAR}</div><div>強化素材 ${state.materials.weapon}/${state.materials.armor}/${state.materials.ring}</div>`;renderEquipped();renderInventory();renderMaterials();renderUpgradeButton();renderBarsOnly()}
function renderEquipped(){const e=$('equipped');e.innerHTML=Object.keys(SLOTS).map(slot=>{const i=state.equipped[slot];return `<div class="equip-card ${selectedEquipSlot===slot?'selected':''}" data-slot="${slot}"><div class="equip-icon">${i?ICON[slot]:'□'}</div><div class="equip-name"><b>${SLOTS[slot]}</b><br>${i?`${i.name} +${i.upgrade||0}<br>戦力 ${power(i)}`:'未装備'}</div></div>`}).join('');e.querySelectorAll('.equip-card').forEach(el=>{const slot=el.dataset.slot;el.onclick=()=>selectEquip(slot);el.onmouseenter=ev=>{const i=state.equipped[slot];if(i)showTip(i,ev.clientX,ev.clientY,true)};el.onmousemove=ev=>{if($('tooltip').classList.contains('show'))moveTip(ev.clientX,ev.clientY)};el.onmouseleave=hideTip})}
function renderMaterials(){$('materials').innerHTML=`<div class="mat-row"><span>${MAT_NAME.weapon}</span><b>${state.materials.weapon}</b></div><div class="mat-row"><span>${MAT_NAME.armor}</span><b>${state.materials.armor}</b></div><div class="mat-row"><span>${MAT_NAME.ring}</span><b>${state.materials.ring}</b></div>`}
function renderUpgradeButton(){const b=$('upgradeBtn'),item=selectedEquipSlot&&state.equipped[selectedEquipSlot];if(!item){b.disabled=true;b.textContent='装備を選択して強化';b.onmouseenter=null;b.onmouseleave=null;return}b.disabled=false;b.textContent=`${item.name} +${item.upgrade||0} を強化`;b.onmouseenter=e=>showUpgradeTip(item,e.clientX,e.clientY);b.onmousemove=e=>moveTip(e.clientX,e.clientY);b.onmouseleave=hideTip}
function renderInventory(){const box=$('inventory');box.innerHTML='';for(let n=0;n<49;n++){const i=state.inventory[n],b=document.createElement('button');b.className='slot '+(i?i.cls:'empty');if(i){b.innerHTML=`<span>${ICON[i.slot]}</span><small>${power(i)}</small>`;b.onclick=e=>{e.stopPropagation();equipItem(i.id)};b.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();showDetail(i,e.clientX,e.clientY)};b.onmouseenter=e=>{if(!$('itemDetail').classList.contains('show'))showTip(i,e.clientX,e.clientY)};b.onmousemove=e=>{if(!$('itemDetail').classList.contains('show'))moveTip(e.clientX,e.clientY)};b.onmouseleave=hideTip}box.appendChild(b)}}
function statRows(i,eq){const keys=[['atk','攻撃'],['def','防御'],['hp','HP'],['speed','速度'],['leech','吸収'],['reduce','軽減'],['crit','会心']];return keys.filter(([k])=>itemBonusValue(i,k)||(eq&&itemBonusValue(eq,k))).map(([k,l])=>{const v=itemBonusValue(i,k),ev=eq?itemBonusValue(eq,k):0,d=v-ev;return `<div>${l}</div><b class="${d>=0?'diff-plus':'diff-minus'}">${v} (${d>=0?'+':''}${d})</b>`}).join('')||'<div>比較なし</div><b>-</b>'}
function tipHTML(i,eqOverride=null){const eq=eqOverride===null?state.equipped[i.slot]:eqOverride,diff=power(i)-power(eq);return `<div class="tip-title">${ICON[i.slot]} ${i.name} +${i.upgrade||0}</div><div class="tip-sub">${i.rarity} / ${SLOTS[i.slot]}</div><div class="compare">${statRows(i,eq)}</div><div class="need">現在装備：${eq?`${eq.name} +${eq.upgrade||0}`:'なし'} / 総合戦力差 ${diff>=0?'+':''}${diff}</div>`}
function showTip(i,x,y,noCompare=false){const t=$('tooltip');t.innerHTML=tipHTML(i,noCompare?null:state.equipped[i.slot]);t.classList.add('show');moveTip(x,y)}
function showUpgradeTip(item,x,y){const group=SLOT_GROUP[selectedEquipSlot],need=(item.upgrade||0)+1,before=clone(item);const after=clone(item);after.upgrade=(after.upgrade||0)+1;const t=$('tooltip');t.innerHTML=`<div class="tip-title">強化予定：${item.name} +${item.upgrade||0} → +${after.upgrade}</div><div class="compare">${statRows(after,before)}</div><div class="need">必要：${MAT_NAME[group]} ×${need} / 所持 ${state.materials[group]}</div>`;t.classList.add('show');moveTip(x,y)}
function showDetail(i,x,y){hideTip();const d=$('itemDetail'),sellGold=Math.max(5,power(i)*4);d.innerHTML=tipHTML(i)+`<div class="detail-buttons"><button onclick="equipItem('${i.id}')">装備する</button><button onclick="sellItem('${i.id}')">売却 +${sellGold}</button><button onclick="hideDetail()">閉じる</button></div>`;d.classList.add('show');moveDetail(x,y)}
function moveTip(x,y){const t=$('tooltip');t.style.left=Math.min(innerWidth-340,Math.max(8,x+16))+'px';t.style.top=Math.min(innerHeight-220,Math.max(8,y-18))+'px'}
function moveDetail(x,y){const d=$('itemDetail');d.style.left=Math.min(innerWidth-340,Math.max(8,x+12))+'px';d.style.top=Math.min(innerHeight-260,Math.max(8,y+12))+'px'}
function hideTip(){$('tooltip').classList.remove('show')} function hideDetail(){$('itemDetail').classList.remove('show')}
function showSlash(){const e=$('slash');e.classList.remove('show');void e.offsetWidth;e.classList.add('show')} function showDamage(txt){const e=$('damageText');e.textContent=txt;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')} function flash(id){const e=$(id);e.classList.remove('hit');void e.offsetWidth;e.classList.add('hit')} function pop(id){const e=$(id);if(!e)return;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
function addLog(html){const l=$('log'),d=document.createElement('div');d.innerHTML=html;l.prepend(d);while(l.children.length>16)l.lastChild.remove()}
function rand(a,b){return Math.floor(a+Math.random()*(b-a+1))}
function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)()}
function play(type){if(state.sound.muted||state.sound.volume<=0)return;try{ensureAudio();const map={hit:[250,.05],crit:[560,.08],win:[660,.09],boss:[170,.18],chest:[850,.12],open:[730,.14],drop:[980,.16],level:[1050,.22],equip:[430,.08],sell:[320,.06],heal:[620,.12],down:[120,.22]};const [f,d]=map[type]||map.hit,now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type==='down'?'sawtooth':'square';o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(Math.max(60,f*.55),now+d);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(state.sound.volume*.12,now+.01);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+d+.02)}catch(e){}}
function renderBarsOnly(){const s=stats();state.hp=Math.min(state.hp,s.maxHp);$('heroHpText').textContent=`${state.hp}/${s.maxHp}`;$('enemyHpText').textContent=`${Math.max(0,enemy.hp)}/${enemy.maxHp}`;$('expText').textContent=`${state.exp}/${expNeed()}`;$('heroHpBar').style.width=(state.hp/s.maxHp*100)+'%';$('enemyHpBar').style.width=(Math.max(0,enemy.hp)/enemy.maxHp*100)+'%';$('expBar').style.width=(state.exp/expNeed()*100)+'%'}
function loop(now){const s=stats();if(!dying&&!spawning&&now-lastHeroAttack>s.interval){heroAttack();lastHeroAttack=now}if(!dying&&!spawning&&now-lastEnemyAttack>1300){enemyAttack();lastEnemyAttack=now}if(now-lastSave>5000){save();lastSave=now}renderBarsOnly();requestAnimationFrame(loop)}
function reset(){if(!confirm('本当にリセットする？'))return;localStorage.removeItem(SAVE_KEY);state=clone(defaultState);enemy=makeEnemy();selectedEquipSlot=null;addLog('リセットした');spawnEnemy();refreshStageSelect();renderAll()}
$('openChestBtn').onclick=openChest;$('sortBtn').onclick=sortInventory;$('bulkSellBtn').onclick=bulkSell;$('debugModeBtn').onclick=toggleDebug;$('debugChestBtn').onclick=debugAddChests;$('upgradeBtn').onclick=upgradeSelected;$('healBtn').onclick=heal;$('saveBtn').onclick=()=>save(true);$('resetBtn').onclick=reset;$('goStage').onclick=changeStage;$('muteBtn').onclick=()=>{state.sound.muted=!state.sound.muted;renderAll();save()};$('volume').oninput=e=>{state.sound.volume=Number(e.target.value)/100;state.sound.muted=state.sound.volume===0;renderAll();save()};window.addEventListener('pointerdown',ensureAudio,{once:true});window.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('click',e=>{if(!e.target.closest('.slot')&&!e.target.closest('#itemDetail'))hideDetail()});
addLog('冒険開始！敵は左、英雄は右。自動で戦うよ。');refreshStageSelect();spawnEnemy();renderAll();requestAnimationFrame(loop);
